name: Release Checker

on:
  pull_request_target:
    paths: [ 'version.json' ]
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-check:
    uses: ipdxco/unified-github-workflows/.github/workflows/release-check.yml@d9b156f4be9fae6843707f5e5cda2fb079f821ac # v1.0.45
